In [1]:
import pandas as pd

In [2]:
pac1=pd.read_csv("webk22/webk22.txt",sep="|",header=None)
pac_cols = pd.read_html("https://www.fec.gov/campaign-finance-data/pac-and-party-summary-file-description/")[0]
pac_cols.columns=pac_cols.iloc[0]
pac_cols=pac_cols[pac_cols['Column name']!='Column name']
pac1.columns=pac_cols['Column name']

In [4]:
pas=pd.read_csv("pas222/itpas2.txt",sep="|",header=None)
pas_cols=pd.read_csv("pas2_header_file.csv")
pas.columns=pas_cols.columns

C:\Users\c_ull\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (10,11,12,19,20) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [90]:
oth=pd.read_csv("oth22/itoth.txt",sep="|",header=None)
oth_cols=pd.read_csv("oth_header_file.csv")
oth.columns=oth_cols.columns

C:\Users\c_ull\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (10,11,12,15,16,18,19) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [5]:
cmte=pd.read_csv("cm22/cm.txt",sep="|",header=None)
cmte_cols=pd.read_csv("cm_header_file.csv")
cmte.columns=cmte_cols.columns

In [61]:
cand=pd.read_csv("cn22/cn.txt",sep="|",header=None)
cand_cols=pd.read_csv("cn_header_file.csv")
cand.columns=cand_cols.columns
cand=cand[cand.CAND_OFFICE_ST=='PA']
parties=['REP','DEM']
cand[(cand.CAND_OFFICE=='S')&(cand.CAND_PTY_AFFILIATION.isin(parties))&(cand.CAND_ELECTION_YR==2022)]
senate_candidates=['S6PA00274',"S2PA00703",'S2PA00661','S2PA00638','S2PA00562','S2PA00489','S2PA00406',
                   'S2PA00398','S2PA00380','S2PA00372',]
senate1=cand[cand.CAND_ID.isin(senate_candidates)]

cand_sum=pd.read_table('weball22/weball22.txt',sep="|",header=None)
weball_cols = pd.read_html("https://www.fec.gov/campaign-finance-data/all-candidates-file-description/")[0]
weball_cols.columns=weball_cols.iloc[0]
weball_cols=weball_cols[weball_cols['Column name']!='Column name']
cand_sum.columns=weball_cols['Column name']
senate_candidates=cand_sum[(cand_sum.CAND_ID.isin(senate1.CAND_ID))&(cand_sum.TTL_RECEIPTS>=1000000)].CAND_ID.to_list()
senate1=senate1[senate1.CAND_ID.isin(senate_candidates)]

In [63]:
keys=senate1.CAND_ID
values=senate1.CAND_NAME
dict1=dict(zip(keys,values))

In [64]:
pas['name1']=pas.CAND_ID.map(dict1)

In [79]:
pas[pas.CAND_ID.isin(senate1.CAND_ID)].groupby(['name1','NAME']).TRANSACTION_AMT.sum().sort_values(ascending=False)#.to_clipboard()

name1                 NAME
BARTOS, JEFF          RESOLVE CAMPAIGNS                   278438
FETTERMAN, JOHN KARL  NEW BLUE INTERACTIVE, LLC            64991
                      SNYDER PICKERILL MEDIA GROUP LLC     44996
LAMB, CONOR           CONOR LAMB FOR CONGRESS              38500
                      CONOR LAMB FOR SENATE                27000
MCCORMICK, DAVE       DAVE MCCORMICK FOR US SENATE         22900
FETTERMAN, JOHN KARL  FETTERMAN FOR PA                     20700
KENYATTA, MALCOLM     MALCOLM PAC                          18250
BARNETTE, KATHY       FRIENDS FOR KATHY BARNETTE           16967
BARTOS, JEFF          BARTOS FOR US SENATE INC             15658
KENYATTA, MALCOLM     MALCOM PAC                           14800
OZ, MEHMET DR.        DOCTOR OZ FOR SENATE                 12838
BARTOS, JEFF          BARTOS FOR US SENATE                  5000
OZ, MEHMET DR.        BLUE WAVE COMMUNICATIONS LLC          5000
BARNETTE, KATHY       BARNETTE, KATHY                       2900
BARTOS, JEFF          BARTOS FOR SENATE INC.                2500
                      BARTOS FOR US SENATE, INC.            1000
LAMB, CONOR           LAMB, CONOR                            500
Name: TRANSACTION_AMT, dtype: int64

In [71]:
cmte[cmte.CMTE_NM.str.contains("RESOLVE")]

,CMTE_ID,CMTE_NM,TRES_NM,CMTE_ST1,CMTE_ST2,CMTE_CITY,CMTE_ST,CMTE_ZIP,CMTE_DSGN,CMTE_TP,CMTE_PTY_AFFILIATION,CMTE_FILING_FREQ,ORG_TP,CONNECTED_ORG_NM,CAND_ID
5256,C00605212,HAVING UNWAVERING RESOLVE AND DETERMINATION PAC,"CRATE, BRADLEY",PO BOX 1000,NaN,BEVERLY,MA,01915,D,Q,NaN,T,NaN,NaN,NaN
9505,C00725671,RESOLVE TO WIN FUND,"NEELEY, BRION",3104 E CAMELBACK RD # 215,NaN,PHOENIX,AZ,85016,U,V,NaN,Q,NaN,NONE,NaN

In [76]:
pas[pas.NAME.str.contains("RESOLVE",na=False)]#.TRANSACTION_AMT.sum()

,CMTE_ID,AMNDT_IND,RPT_TP,TRANSACTION_PGI,IMAGE_NUM,TRANSACTION_TP,ENTITY_TP,NAME,CITY,STATE,...,TRANSACTION_DT,TRANSACTION_AMT,OTHER_ID,CAND_ID,TRAN_ID,FILE_NUM,MEMO_CD,MEMO_TEXT,SUB_ID,name1
312050,C00750182,N,M2,P2022,202202199491829879,24E,ORG,RESOLVE CAMPAIGNS LLC,AUSTIN,TX,...,1072022.0,3000,H0TX07170,H0TX07170,SE.5390,1570884,NaN,NaN,4022220221424199051,NaN
312053,C00750182,N,M2,P2022,202202199491829878,24E,ORG,RESOLVE CAMPAIGNS LLC,AUSTIN,TX,...,1042022.0,8000,H0TX07170,H0TX07170,SE.5386,1570884,NaN,NaN,4022220221424199049,NaN
312054,C00750182,N,M2,P2022,202202199491829878,24E,ORG,RESOLVE CAMPAIGNS LLC,AUSTIN,TX,...,1072022.0,8000,H0TX07170,H0TX07170,SE.5389,1570884,NaN,NaN,4022220221424199050,NaN
312055,C00750182,N,M2,P2022,202202199491829881,24E,ORG,RESOLVE CAMPAIGNS LLC,AUSTIN,TX,...,1272022.0,18167,H0TX07170,H0TX07170,SE.5522,1570884,NaN,NaN,4022220221424199055,NaN
312056,C00750182,N,M2,P2022,202202199491829879,24E,ORG,RESOLVE CAMPAIGNS LLC,AUSTIN,TX,...,1072022.0,29799,H0TX07170,H0TX07170,SE.5391,1570884,NaN,NaN,4022220221424199052,NaN
312057,C00750182,N,M2,P2022,202202199491829880,24E,ORG,RESOLVE CAMPAIGNS LLC,AUSTIN,TX,...,1072022.0,5044,H0TX07170,H0TX07170,SE.5392,1570884,NaN,NaN,4022220221424199053,NaN
312058,C00750182,N,M2,P2022,202202199491829880,24E,ORG,RESOLVE CAMPAIGNS LLC,AUSTIN,TX,...,1202022.0,21654,H0TX07170,H0TX07170,SE.5519,1570884,NaN,NaN,4022220221424199054,NaN
317217,C00750182,N,M3,P2022,202203209494143640,24E,ORG,RESOLVE CAMPAIGNS LLC,AUSTIN,TX,...,2012022.0,29356,H0TX07170,H0TX07170,SE.5524,1575885,NaN,NaN,4032320221464062145,NaN
317218,C00750182,N,M3,P2022,202203209494143640,24E,ORG,RESOLVE CAMPAIGNS LLC,AUSTIN,TX,...,2012022.0,3880,H0TX07170,H0TX07170,SE.5525,1575885,NaN,NaN,4032320221464062146,NaN
317219,C00750182,N,M3,P2022,202203209494143641,24E,ORG,RESOLVE CAMPAIGNS LLC,AUSTIN,TX,...,2162022.0,10031,H0TX07170,H0TX07170,SE.5548,1575885,NaN,NaN,4032320221464062147,NaN
317220,C00750182,N,M3,P2022,202203209494143641,24E,ORG,RESOLVE CAMPAIGNS LLC,AUSTIN,TX,...,2162022.0,1243,H0TX07170,H0TX07170,SE.5549,1575885,NaN,NaN,4032320221464062148,NaN
317221,C00750182,N,M3,P2022,202203209494143642,24E,ORG,RESOLVE CAMPAIGNS LLC,AUSTIN,TX,...,2242022.0,79140,H0TX35015,H0TX35015,SE.5556,1575885,NaN,NaN,4032320221464062149,NaN
317222,C00750182,N,M3,P2022,202203209494143642,24E,ORG,RESOLVE CAMPAIGNS LLC,AUSTIN,TX,...,2242022.0,12663,H0TX35015,H0TX35015,SE.5557,1575885,NaN,NaN,4032320221464062150,NaN
317223,C00750182,N,M3,P2022,202203209494143643,24E,ORG,RESOLVE CAMPAIGNS LLC,AUSTIN,TX,...,2242022.0,7000,H0TX35015,H0TX35015,SE.5558,1575885,NaN,NaN,4032320221464062151,NaN
324009,C90021288,N,Q1,P2022,202204119496021413,24E,ORG,RESOLVE CAMPAIGNS,AUSTIN,TX,...,3302022.0,278438,S2PA00380,S2PA00380,F57.000001,1579696,NaN,NaN,4041320221470644000,"BARTOS, JEFF"

In [19]:
cmte[cmte.CMTE_ID.isin(pas.OTHER_ID)]

,CMTE_ID,CMTE_NM,TRES_NM,CMTE_ST1,CMTE_ST2,CMTE_CITY,CMTE_ST,CMTE_ZIP,CMTE_DSGN,CMTE_TP,CMTE_PTY_AFFILIATION,CMTE_FILING_FREQ,ORG_TP,CONNECTED_ORG_NM,CAND_ID
130,C00012229,ALASKANS FOR DON YOUNG,"THAYER, CURTIS",2504 FAIRBANKS ST,NaN,ANCHORAGE,AK,99503,P,H,REP,Q,NaN,TAKE BACK THE HOUSE 2020,H6AK00045
140,C00013128,CONGRESSMAN WAXMAN CAMPAIGN COMMITTEE,"PADILLA, MARY ELLEN","6380 WILSHIRE BLVD., #1612",NaN,LOS ANGELES,CA,90048,P,H,DEM,Q,NaN,LA PAC,H6CA24048
348,C00068353,LEAHY FOR U.S. SENATOR COMMITTEE,ROBERT S DIPALMA,PO BOX 1042,NaN,MONTPELIER,VT,05601,P,S,NaN,Q,NaN,NaN,S4VT00017
411,C00083428,SENSENBRENNER COMMITTEE,"SAVAGE, JOHN P.",PO BOX 575,NaN,BROOKFIELD,WI,53008,P,H,REP,Q,NaN,NaN,H8WI09050
471,C00096412,FRIENDS OF CHRIS SMITH,"ROLDAN, MARY MRS.",PO BOX 3184,NaN,HAMILTON,NJ,086190184,P,H,REP,Q,NaN,CHRIS SMITH VICTORY FUND,H8NJ04014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16641,C00807743,FINSTAD FOR CONGRESS,"DATWYLER, THOMAS",PO BOX 923,NaN,NEW ULM,MN,56073,P,H,REP,Q,NaN,NONE,H2MN01223
16688,C00808279,JOHN DUARTE FOR CONGRESS,"LAWLER, KELLY",9460 TEGNER ROAD,NaN,HILMAR,CA,95324,P,H,REP,Q,NaN,NONE,H2CA13131
16712,C00808519,COMMITTEE TO ELECT MICHAEL CASSIDY,"DATWYLER, THOMAS",P.O. BOX 452,NaN,LAUDERDALE,MS,39335,P,H,REP,Q,NaN,NONE,H2MS03151
16817,C00809608,DENNIS ROSS FOR CONGRESS,"ROBINSON, ERIC WAYNE",3310 CLEVELAND HEIGHTS,SUITE 204,LAKELAND,FL,33803,P,H,REP,Q,NaN,NONE,H2FL15217
16896,C00810416,JENNIFER SCHULTZ VOLUNTEER COMMITTEE,"WEIDNER, ROBERT",P.O. BOX 3218,NaN,DULUTH,MN,55803,P,H,DFL,Q,NaN,NONE,H2MN08152

In [29]:
pas[(pas.OTHER_ID.isin(cmte.CMTE_ID))&(pas.name1.notna())&(pas.ENTITY_TP=='PAC')].NAME.value_counts()

BRIAN FITZPATRICK FOR ALL OF US    9
MAD 4 PA PAC                       8
FRIENDS OF GLENN THOMPSON          6
CHRISSY HOULAHAN FOR CONGRESS      3
SCANLON FOR CONGRESS               3
MAD4PA PAC                         3
DWIGHT EVANS FOR CONGRESS          2
SHARIF STREET FOR PA               2
CARTWRIGHT FOR CONGRESS            2
SCHELLER FOR CONGRESS, INC.        2
SMUCKER FOR CONGRESS               1
FRIENDS OF FRED KELLER             1
CITIZENS FOR BOYLE                 1
BOB CASEY FOR SENATE INC           1
FRED KELLER FOR CONGRESS           1
CONOR LAMB FOR CONGRESS            1
MORAN PAC                          1
BRINGING AMERICA TOGETHER PAC      1
MIKE KELLY FOR CONGRESS            1
BARTOS FOR US SENATE INC           1
HOULAHAN, CHRISSY                  1
SUSAN WILD FOR CONGRESS            1
HOUSE FREEDOM FUND                 1
Name: NAME, dtype: int64

In [24]:
pas[(pas.CMTE_ID.isin(cmte.CMTE_ID))&(pas.name1.notna())].NAME.value_counts().head(50)

PATRIOTS FOR PERRY                  1131
BRIAN FITZPATRICK FOR ALL OF US      862
AMERICANS FOR PARNELL COMMITTEE      431
CARTWRIGHT FOR CONGRESS              397
FRIENDS OF GLENN THOMPSON            367
CHRISSY HOULAHAN FOR CONGRESS        316
SUSAN WILD FOR CONGRESS              284
CITIZENS FOR BOYLE                   281
GUY FOR CONGRESS                     251
MIKE KELLY FOR CONGRESS              206
MAD 4 PA PAC                         193
DWIGHT EVANS FOR CONGRESS            175
BOB CASEY FOR SENATE INC             146
SCANLON FOR CONGRESS                 144
SMUCKER FOR CONGRESS                 139
DR JOHN JOYCE FOR CONGRESS           133
MEUSER FOR CONGRESS                  132
BRIAN FITZPATRICK FOR CONGRESS       129
BARTOS FOR US SENATE INC             105
BOGNET FOR CONGRESS                  104
CONOR LAMB FOR CONGRESS               82
SCHELLER FOR CONGRESS, INC.           80
FRED KELLER FOR CONGRESS              77
DOYLE FOR CONGRESS COMMITTEE          76
FRIENDS OF PAT TOOMEY                 66
HOUSE FREEDOM FUND                    64
DOCTOR OZ FOR SENATE                  36
MAD4PA PAC                            35
DR. JOHN JOYCE FOR CONGRESS           33
FRIENDS FOR KATHY BARNETTE            30
NEW BLUE INTERACTIVE, LLC             21
ANALYTICS NINJA                       19
CONOR LAMB FOR SENATE                 14
VAL ARKOOSH FOR US SENATE             14
SNYDER PICKERILL MEDIA GROUP LLC      14
DCCC                                  10
SHARIF STREET FOR PA                  10
BOB CASEY FOR SENATE INC.              9
DEPASQUALE FOR PA 10                   8
MALCOLM PAC                            7
FETTERMAN FOR PA                       7
ALLIANCE STRATEGIES GROUP, INC.        7
SANDS FOR SENATE                       7
THOMPSON, GLENN MR.                    6
SIERRA CLUB                            6
SCHELLER FOR CONGRESS INC.             6
SCHELLER FOR CONGRESS                  6
HOULAHAN, CHRISSY                      6
MALCOM PAC                             5
THOMPSON, FRIENDS OF GLENN             5
Name: NAME, dtype: int64

In [87]:
camp[camp.CAND_ID.isin(senate1.CAND_ID)].columns

Index(['CAND_ID', 'CAND_NAME', 'CAND_ICI', 'PTY_CD', 'CAND_PTY_AFFILIATION',
       'TTL_RECEIPTS', 'TRANS_FROM_AUTH', 'TTL_DISB', 'TRANS_TO_AUTH',
       'COH_BOP', 'COH_COP', 'CAND_CONTRIB', 'CAND_LOANS', 'OTHER_LOANS',
       'CAND_LOAN_REPAY', 'OTHER_LOAN_REPAY', 'DEBTS_OWED_BY',
       'TTL_INDIV_CONTRIB', 'CAND_OFFICE_ST', 'CAND_OFFICE_DISTRICT',
       'SPEC_ELECTION', 'PRIM_ELECTION', 'RUN_ELECTION', 'GEN_ELECTION',
       'GEN_ELECTION_PRECENT', 'OTHER_POL_CMTE_CONTRIB', 'POL_PTY_CONTRIB',
       'CVG_END_DT', 'INDIV_REFUNDS', 'CMTE_REFUNDS'],
      dtype='object', name='Column name')

In [40]:
cmte[(cmte.CMTE_ID.isin(pas[pas.CAND_ID.str.contains("PA",na=False)].CMTE_ID))]

,CMTE_ID,CMTE_NM,TRES_NM,CMTE_ST1,CMTE_ST2,CMTE_CITY,CMTE_ST,CMTE_ZIP,CMTE_DSGN,CMTE_TP,CMTE_PTY_AFFILIATION,CMTE_FILING_FREQ,ORG_TP,CONNECTED_ORG_NM,CAND_ID
1,C00000422,AMERICAN MEDICAL ASSOCIATION POLITICAL ACTION ...,"WALKER, KEVIN MR.","25 MASSACHUSETTS AVE, NW",SUITE 600,WASHINGTON,DC,200017400,B,Q,NaN,M,NaN,ALABAMA MEDICAL PAC,NaN
4,C00000729,AMERICAN DENTAL ASSOCIATION POLITICAL ACTION C...,"FAIR, JULIAN H DR. III","1111 14TH STREET, NW",SUITE 1100,WASHINGTON,DC,200055627,B,Q,UNK,M,M,NaN,NaN
5,C00000885,INTERNATIONAL UNION OF PAINTERS AND ALLIED TRA...,"SMITH, GREGG",7234 PARKWAY DRIVE,NaN,HANOVER,MD,21076,B,Q,UNK,M,L,INTERNATIONAL UNION OF PAINTERS AND ALLIED TRADES,NaN
6,C00000901,BUILD POLITICAL ACTION COMMITTEE OF THE NATION...,"RAMAGE, EILEEN","1201 15TH STREET, NW",NaN,WASHINGTON,DC,20005,B,Q,UNK,M,T,NATIONAL ASSOCIATION OF HOME BUILDERS,NaN
7,C00000935,DCCC,"PERSICO, TIMOTHY","430 SOUTH CAPITOL STREET, SE",2ND FLOOR,WASHINGTON,DC,200034024,U,Y,DEM,M,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14538,C00786202,CROSSPARTISAN PAC II,"KOCH, TIMOTHY A.",PO BOX 1843,NaN,ALEXANDRIA,VA,22313,U,Q,NaN,M,NaN,NaN,NaN
14556,C00786392,MA 4 DEMS PAC,"MURRAY, ALLISON P.",PO BOX 600698,NaN,NEWTONVILLE,MA,02460,D,Q,NaN,M,NaN,AUCHINCLOSS,NaN
16169,C00802942,FROM PA FOR PA,"DATWYLER, THOMAS",499 SOUTH CAPITOL STREET SW,#405,WASHINGTON,DC,20003,U,O,NaN,Q,NaN,NONE,NaN
17474,C90011800,CATHOLICVOTE.ORG,"MERCER, JOSHUA",PO BOX 2709,NaN,CHICAGO,IL,60690,U,I,NaN,Q,NaN,NaN,NaN
18090,C90021288,BE COUNTED,NaN,191 W NATIONWIDE BLVD,SUITE 300,COLUMBUS,OH,43215,U,I,NaN,Q,NaN,NaN,NaN

In [33]:
cmte[cmte.TRES_NM.str.contains("MARTINO",na=False)]

,CMTE_ID,CMTE_NM,TRES_NM,CMTE_ST1,CMTE_ST2,CMTE_CITY,CMTE_ST,CMTE_ZIP,CMTE_DSGN,CMTE_TP,CMTE_PTY_AFFILIATION,CMTE_FILING_FREQ,ORG_TP,CONNECTED_ORG_NM,CAND_ID
3603,C00487298,RIVER HORSE PAC,"MARTINO, PAUL",5 THEODORE WAY,NaN,DOYLESTOWN,PA,18901,U,N,NaN,Q,NaN,NONE,NaN

In [35]:
cmte[cmte.CMTE_CITY=='DOYLESTOWN']

,CMTE_ID,CMTE_NM,TRES_NM,CMTE_ST1,CMTE_ST2,CMTE_CITY,CMTE_ST,CMTE_ZIP,CMTE_DSGN,CMTE_TP,CMTE_PTY_AFFILIATION,CMTE_FILING_FREQ,ORG_TP,CONNECTED_ORG_NM,CAND_ID
3603,C00487298,RIVER HORSE PAC,"MARTINO, PAUL",5 THEODORE WAY,NaN,DOYLESTOWN,PA,18901,U,N,NaN,Q,NaN,NONE,NaN
10239,C00736330,FRIENDS OF STEVE SCHEETZ,"BURTON, KYLE",C/O WASSMER AGENCY SERVICES LLC,"171 S MAIN STREET, 2ND FLOOR",DOYLESTOWN,PA,18901,P,H,LIB,T,NaN,NaN,H0PA01341
12129,C00760835,LOSERS AND SUCKERS VOTE,"MASTERS, STEVE",PO BOX 2172,NaN,DOYLESTOWN,PA,18901,U,O,NaN,Q,NaN,NONE,NaN

In [36]:
pas[pas.CMTE_ID=='C00760835']

Empty DataFrame
Columns: [CMTE_ID, AMNDT_IND, RPT_TP, TRANSACTION_PGI, IMAGE_NUM, TRANSACTION_TP, ENTITY_TP, NAME, CITY, STATE, ZIP_CODE, EMPLOYER, OCCUPATION, TRANSACTION_DT, TRANSACTION_AMT, OTHER_ID, CAND_ID, TRAN_ID, FILE_NUM, MEMO_CD, MEMO_TEXT, SUB_ID, name1]
Index: []

[0 rows x 23 columns]

In [92]:
oth.columns

Index(['CMTE_ID', 'AMNDT_IND', 'RPT_TP', 'TRANSACTION_PGI', 'IMAGE_NUM',
       'TRANSACTION_TP', 'ENTITY_TP', 'NAME', 'CITY', 'STATE', 'ZIP_CODE',
       'EMPLOYER', 'OCCUPATION', 'TRANSACTION_DT', 'TRANSACTION_AMT',
       'OTHER_ID', 'TRAN_ID', 'FILE_NUM', 'MEMO_CD', 'MEMO_TEXT', 'SUB_ID'],
      dtype='object')

In [100]:
oth[oth.NAME.str.upper().str.contains("DUPONT,",na=False)].NAME.value_counts()

DUPONT, ANTHONY              18
DUPONT, DIANA                 8
DUPONT, CYNTHIA MS.           7
DUPONT, JULES S               5
DUPONT, PHILIPPE A. MR.       4
DUPONT, JACQUELINE L          4
DUPONT, BENJAMIN              3
DUPONT, JACQUELINE L. DR.     2
FORESTEIRE DUPONT, ANGELA     2
DUPONT, DIANA MS.             2
DUPONT, STEPHEN               2
DUPONT, CYNTHOA               1
DUPONT, RICHARD E. MR.        1
DUPONT, CYNTHIA               1
DUPONT, MICHELLE              1
DUPONT, ANNE T                1
Name: NAME, dtype: int64

In [114]:
oth[oth.CMTE_ID=='C00794891']

Empty DataFrame
Columns: [CMTE_ID, AMNDT_IND, RPT_TP, TRANSACTION_PGI, IMAGE_NUM, TRANSACTION_TP, ENTITY_TP, NAME, CITY, STATE, ZIP_CODE, EMPLOYER, OCCUPATION, TRANSACTION_DT, TRANSACTION_AMT, OTHER_ID, TRAN_ID, FILE_NUM, MEMO_CD, MEMO_TEXT, SUB_ID]
Index: []

[0 rows x 21 columns]

In [122]:
pac1[pac1.CMTE_NM.str.contains("AMERICAN LEADERSHIP ACTION")]#.TTL_DISB

Column name,CMTE_ID,CMTE_NM,CMTE_TP,CMTE_DSGN,CMTE_FILING_FREQ,TTL_RECEIPTS,TRANS_FROM_AFF,INDV_CONTRIB,OTHER_POL_CMTE_CONTRIB,CAND_CONTRIB,...,LOAN_REPAY,COH_BOP,COH_COP,DEBTS_OWED_BY,NONFED_TRANS_RECEIVED,CONTRIB_TO_OTHER_CMTE,IND_EXP,PTY_COORD_EXP,NONFED_SHARE_EXP,CVG_END_DT
9847,C00794891,AMERICAN LEADERSHIP ACTION,O,U,Q,3197602.31,0.0,3197602.31,0.0,0.0,...,0.0,0.0,477678.11,0.0,0.0,0.0,2329350.34,0.0,0.0,03/31/2022

In [121]:
cmte[cmte.CMTE_NM.str.contains("AMERICAN LEADERSHIP")]

,CMTE_ID,CMTE_NM,TRES_NM,CMTE_ST1,CMTE_ST2,CMTE_CITY,CMTE_ST,CMTE_ZIP,CMTE_DSGN,CMTE_TP,CMTE_PTY_AFFILIATION,CMTE_FILING_FREQ,ORG_TP,CONNECTED_ORG_NM,CAND_ID
3673,C00490961,CHINESE AMERICAN LEADERSHIP POLITICAL ACTION C...,"HA, JULIAN",8421 HOLLY LEAF DRIVE,NaN,MCLEAN,VA,22102,U,N,NaN,Q,NaN,NONE,NaN
4207,C00528760,POLISH AMERICAN LEADERSHIP POLITICAL ACTION CO...,"KURZYDLOWSKI, MICHELLE",2500 RAVINE WAY,NaN,GLENVIEW,IL,60025,U,O,NaN,Q,NaN,NONE,NaN
5324,C00610147,RESTORE AMERICAN LEADERSHIP,"GANTT, CHARLES",138 CONANT STREET,SUITE 200,BEVERLY,MA,01915,U,O,NaN,Q,NaN,NONE,NaN
11593,C00754283,PATRIOTS FOR AMERICAN LEADERSHIP,"SHIVERS, EDDIE",PO BOX 46295,NaN,PHOENIX,AZ,85063,D,N,NaN,Q,NaN,NONE,NaN
12332,C00763243,CAMPAIGN TO SUPPORT AMERICAN LEADERSHIP,"DATWYLER, THOMAS C.",PO BOX 183,NaN,HUDSON,WI,54016,U,N,NaN,T,NaN,NaN,NaN
15387,C00794891,AMERICAN LEADERSHIP ACTION,"REISNER, MICHELE",3804 WILSON BLVD BOX 1065,NaN,ARLINGTON,VA,22203,U,O,NaN,Q,NaN,NONE,NaN